services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongodb
    build: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080

  volumes:
    db: